name: Node Github CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
        env:
          CI: true

  deploy:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy node app
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        uses: appleboy/ssh-action@master
        with:
          host: $HOST
          username: $USER
          key: $PRIVATE_KEY
          script: |
            cd ~/services/mh1-backend
            git pull origin main
            npm ci --only=production
            npx mikro-orm migration:create
            npx mikro-orm migration:up
            npm run build
            pm2 restart mh1_backend
